# Generated by Django 3.1.5 on 2021-02-06 08:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prdsolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='State',
            new_name='State_name',
        ),
        migrations.AlterField(
            model_name='city',
            name='District',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='State_name', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='prdsolapp.district'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('cityname',)},
        ),
    ]
