# Generated by Django 3.1.5 on 2021-02-06 08:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prdsolapp', '0002_auto_20210206_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Branch_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='City', chained_model_field='cityname', on_delete=django.db.models.deletion.CASCADE, to='prdsolapp.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('cityname', 'State_name', 'District')},
        ),
    ]
