# Generated by Django 3.1.5 on 2021-02-06 08:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('prdsolapp', '0003_auto_20210206_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='City',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='District', chained_model_field='District', on_delete=django.db.models.deletion.CASCADE, to='prdsolapp.city'),
        ),
    ]
