# Generated by Django 3.1.5 on 2021-02-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prdsolapp', '0007_auto_20210217_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branch'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='keyskill',
            options={'verbose_name_plural': 'Key Skill'},
        ),
    ]
